### ISSUE TITLE
Multipart support & incoming signature verification

### ISSUE THREAD

**Issue by ghost** [php-soap/psr18-wsse-middleware#13]
Could you implement multipart support and signature verification on incoming response ?

Thanks

Regards

Michael

**Comment by veewee** [comment]
Hello @michael79bxl ,

Care to share a bit more about what you are trying to achieve exactly?
Are you talking about something like MTOM / SwA support? Because that would probably be a different layer than WSSE.

To answer your question "Could you implement x ?":

We won't implement this if we don't have a need for this ourselves.
However, if you care to get this feature in the project - there are some ways forward:

* You can create a PR and we can guide you through the process of getting this implementation in here.
* You can [hire us to do your implementation](https://github.com/php-soap/.github/blob/main/HELPING_OUT.md#let-us-do-your-implementation). Tis way we can help you getting the job done. Not only do we invest a part of the income back into the project, we can take the learnings from the project and make the feature available for everyone. It's a big win win for everyone involved and some future users.
